engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
  csslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths:
  - db/
  - /node_modules/
  - /client/build/
  - scripts/lib/
  - webpack.config.js
  - test/